
eureka:
  client:
    security:
      basic:
        user: admin
        password: admin
    serviceUrl:
      # defaultZone: http://localhost:9761/eureka/
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:9761/eureka/ # Http basic配置

server:
  port: 9769

spring:
  application:
    name: zuul-server

# 支持通配符配置
zuul:
  prefix: /zull
  routes:
    api-a:
      path: /ribbon/**
      serviceId: ribbon-server
    api-b:
      path: /feign/**
      serviceId: feign-server
    api-c:
      path: /provider/**
      serviceId: service-hi
