spring:
  application:
    name: auth-server

server:
  port: 9800
  servlet:
    contextPath: /auth #web基路径

eureka:
  client:
    security:
      basic:
        user: admin
        password: admin
    serviceUrl:
      # defaultZone: http://localhost:9761/eureka/
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:9761/eureka/ # Http basic配置