
server:
  port: 9764

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: ribbon-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"