
server:
  port: 9763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-hi
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: testhost
    username: admin
    password: 123123
    cloud:
      bus:
        enabled: true
        trace:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



project:
  name: wangqi