
server:
  port: 9762

eureka:
  client:
    security:
      basic:
        user: admin
        password: admin
    serviceUrl:
      # defaultZone: http://localhost:9761/eureka/ # 常规配置
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:9761/eureka/ # Http basic配置

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-hi

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"