
server:
  port: 9759

spring:
  application:
    name: zuul-server-limit

eureka:
  client:
    security:
      basic:
        user: admin
        password: admin
    serviceUrl:
      # defaultZone: http://localhost:9761/eureka/
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:9761/eureka/ # Http basic配置

# 支持通配符配置
zuul:
  routes:
    api-c:
      path: /provider/**
      serviceId: service-hi
  ratelimit:
    enabled: true
    default-policy:
      limit: 1
      quota: 2
      refresh-interval: 3

